### ISSUE TITLE
/etc/hpnssh/sshd_config and `Include /etc/ssh/sshd_config.d/*.conf`

### ISSUE THREAD

**Issue by gdevenyi** [rapier1/hpn-ssh#71]
The default config is `Including` the configuration from the system sshd.

Should this instead by `Include /etc/hpnssh/sshd_config.d/*.conf`?

**Comment by gdevenyi** [comment]
Got it, makes sense, I can definitely understand the motivation

**Comment by rapier1** [comment]
I'll make a decision for the next release (hopefully next week as 9.7 recently came out) and document it if that changes. I'll keep this open for now just to remind me. As an aside, I did update the documentation about the ports, port fallback, and ConnectTimeout in the man pages. That will be available in the 18.4.0 release.

**Comment by rapier1** [comment]
I've changed the default location for Includes to point at /etc/hpnssh/ssh[d]_config.d/. Turns out that I'm also doing that the the Fedora release so I might as well keep it consistent. This likely won't break any/many installs because it looks like Ubuntu doesn't make use of /etc/ssh/ssh[d].config.d/ in their release.
